Layout/ExtraSpacing:
  Exclude:
    - lib/lightning/transactions/scripts.rb

Layout/SpaceAroundOperators:
  Exclude:
    - lib/lightning/transactions/scripts.rb

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 140

RaiseArgs:
  EnforcedStyle: compact

RSpec/ExampleWording:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false
